/**
 * `signatures` -- every entry's categorical identity, without reading a single entry.
 *
 * This is what a sampler chooses from. A sampler needs to know what each entry IS -- which
 * categorical value it holds for each property -- and nothing else: not the properties document, not
 * the envelope, and above all not `evidence_text`, which on a real corpus is prose and is the one
 * thing this store is careful never to pull into a caller's memory in bulk. So the projection is
 * built in SQL, one expression per property, and the row that comes back carries labels rather than
 * documents.
 *
 * **THE STATE IS RETURNED, NOT COLLAPSED.** A property that was not measured and a property that was
 * not applicable are different facts (`packages/core/src/state.ts`), and they are different strata:
 * an entry that could not have a value is not the same as one that did not. The state column is
 * generated by `stateCase` -- the same function the generated views and the cross-project union use
 * -- rather than written again here, because a second copy of that CASE is a second answer to "what
 * state is this row in", and two answers that disagree would both look plausible.
 *
 * **A boolean reads as `true`/`false`, not `1`/`0`.** `json_extract` returns SQLite's integer for a
 * JSON boolean, so coercing it in JavaScript afterwards cannot tell `true` from the number `1`. The
 * CASE below asks `json_type` first, which can. A stratum labelled `1` would be a wrong answer of
 * the quiet kind.
 *
 * **Ordered by id.** The sampler sorts by id itself, so this is belt and braces rather than the
 * guarantee -- but it also makes the projection's own output stable for a caller that does not
 * sample at all, and a query whose row order is unspecified is a query whose result a reader cannot
 * compare between runs.
 */

import type { DatabaseSync } from 'node:sqlite';
import { literal, stateCase, type EntryState } from './sql.js';

/** One property's state and value for one entry. */
export interface SignatureCell {
  readonly state: EntryState;
  /** The measured value, or `null` in either absent state -- where there is no value to report. */
  readonly value: string | null;
}

/** One entry's categorical identity: its id, and one cell per property asked for. */
export interface EntrySignature {
  readonly id: string;
  readonly values: Readonly<Record<string, SignatureCell>>;
}

/** A property to project, and the versions that declare it -- which `stateCase` needs. */
export interface SignatureProperty {
  readonly name: string;
  /**
   * Versions of this type that declare the property, ascending.
   *
   * Passed rather than assumed because it is what separates `not_measured` from `not_declared`: a
   * row recorded under a version that never declared the property is in the fourth state, and a
   * projection that treated it as merely unmeasured would report a definition gap as a data gap.
   */
  readonly declaringVersions: readonly number[];
}

/**
 * A property's value, as text.
 *
 * The `ELSE` arm is a bare `json_extract`, which yields a string for a JSON string, an integer or
 * real for a number, and `NULL` for a JSON `null`. Everything except `NULL` is stringified by the
 * caller; `NULL` becomes the cell's `null`, which for a value the vocabulary does not admit is the
 * same answer the three-state model gives it -- `state.ts` documents that collapse, and the recorder
 * refuses a `null` for every type in the vocabulary, so it is reachable only for a row written
 * around this store.
 */
function valueExpr(property: string): string {
  const path = literal(`$.${property}`);
  return (
    `CASE json_type(e.properties_json, ${path})` +
    ` WHEN 'true' THEN 'true' WHEN 'false' THEN 'false'` +
    ` ELSE json_extract(e.properties_json, ${path}) END`
  );
}

/**
 * The categorical identity of every entry of a type.
 *
 * **Property names reach this SQL as text, and that is safe for a reason worth stating.** They are
 * interpolated into a `'$.<name>'` literal path, so a name containing a quote would break the
 * statement -- and it cannot: `canonicalName` (`@ascend/core`) reduces every name to `[a-z0-9_]` at
 * registration, so what is stored in `spec_json` and handed here has no quote, no `$` and no
 * separator left in it. Asserted here rather than assumed, because the assertion is three lines and
 * the failure it prevents is a generated statement that means something other than what it says.
 */
export function signatures(
  db: DatabaseSync,
  type: string,
  properties: readonly SignatureProperty[],
): readonly EntrySignature[] {
  for (const property of properties) {
    if (!/^[a-z0-9_]+$/.test(property.name)) {
      throw new Error(
        `signatures: property name '${property.name}' is not a canonical name, so it cannot be ` +
          `projected without escaping`,
      );
    }
  }

  if (properties.length === 0) {
    const ids = db
      .prepare('SELECT e.id AS id FROM entries AS e WHERE e.type_name = ? ORDER BY e.id')
      .all(type) as unknown as { id: string }[];
    return ids.map((row) => ({ id: row.id, values: {} }));
  }

  const projections = properties.flatMap((property, position) => [
    `${stateCase(property.name, property.declaringVersions)} AS s${String(position)}`,
    `${valueExpr(property.name)} AS v${String(position)}`,
  ]);

  const rows = db
    .prepare(
      `SELECT e.id AS id, ${projections.join(', ')}\n` +
        `  FROM entries AS e WHERE e.type_name = ? ORDER BY e.id`,
    )
    .all(type) as unknown as Record<string, unknown>[];

  return rows.map((row) => {
    const values: Record<string, SignatureCell> = {};
    for (const [position, property] of properties.entries()) {
      const state = row[`s${String(position)}`];
      const held = row[`v${String(position)}`];
      values[property.name] = {
        // The CASE is generated by `stateCase` and its arms are exhaustive, so an unrecognised
        // string here would mean the generated SQL had changed shape -- worth saying rather than
        // defaulting, since a default would silently report a fourth state as one of the three.
        state: asState(state, property.name),
        value: asValue(held, property.name),
      };
    }
    return { id: String(row['id']), values };
  });
}

/**
 * A projected value as text, or `null` where there is no value to report.
 *
 * `json_extract` yields a string for a JSON string and a number for a number, and `valueExpr` has
 * already turned the two boolean keywords into text -- so anything else here means the generated SQL
 * changed shape. Refused rather than stringified, because a bare `String()` would render a value the
 * vocabulary does not admit as `[object Object]`, which is a stratum label a reader has no way to
 * question. Same discipline as `asState` below, and for the same reason.
 */
function asValue(held: unknown, property: string): string | null {
  if (held === null || held === undefined) return null;
  if (typeof held === 'string') return held;
  if (typeof held === 'number') return String(held);
  throw new Error(
    `signatures: property '${property}' projected an unreadable value of type ${typeof held}`,
  );
}

/** Narrows a projected state to the vocabulary, refusing anything else. */
function asState(held: unknown, property: string): EntryState {
  if (
    held === 'measured' ||
    held === 'not_applicable' ||
    held === 'not_measured' ||
    held === 'not_declared'
  ) {
    return held;
  }
  throw new Error(
    `signatures: property '${property}' projected an unreadable state: ${String(held)}`,
  );
}
