/**
 * The entry document: what a recorder writes, and what `asc record` reads.
 *
 * ```jsonc
 * // one entry
 * { "properties": { "chosen": "walk up", "rationale": "…" }, "na": ["reversibility"] }
 *
 * // a batch: an array of the same shape
 * [ { "properties": { … } }, { "properties": { … }, "id": "…" } ]
 * ```
 *
 * **One object or an array of them, and nothing else.** Both spellings are accepted because the
 * batch case is not a different kind of thing -- it is the same document, several times -- and a
 * caller that has one entry in hand should not have to know whether to wrap it. An empty array is
 * refused: it means a caller whose generator produced nothing, and reporting "0 entries recorded"
 * with exit 0 would call that success.
 *
 * **`properties` is nested rather than spread across the top level, and that is a correctness
 * decision rather than a style one.** A type may declare a property called `id`, `version` or
 * `na`, and a document that flattened property names into the top level could not say which one a
 * key meant -- so the ambiguity would be resolved by whichever branch happened to run first, and
 * the entry would record something the caller did not write. Nesting makes the two namespaces
 * disjoint by construction, so there is nothing to resolve.
 *
 * **Some keys are refused with a reason rather than merely being unknown**, and those refusals are
 * the interesting part of this file:
 *
 *   - `source` -- `self` and `derived:claude-code` are a claim about *provenance*: that a machine
 *     derived this from a transcript rather than someone observing it. It is the one column that
 *     tells real observation from inference, and a hand-written or model-written document asserting
 *     it would corrupt exactly the distinction it exists to draw. The adapter that derives entries
 *     writes them through the store (`recorder.ts`), not through this command.
 *   - `recorded_at` -- the clock belongs to `BaseCommand.now()`. A document that could set its own
 *     timestamp could backdate an entry, and the ledger's whole chronological value rests on
 *     `recorded_at` being what ascend observed rather than what a caller claimed.
 *   - `cwd` -- mechanically derivable, so it is read from the process rather than asked for
 *     (`asc-kwr`'s principle: never make a caller self-report what can be read off disk). `repo`,
 *     `git_sha` and `branch` are the same argument and are not read yet: they mean spawning `git`
 *     on the hot path `asc-9y1` exists to measure, and E5's adapter is where derived envelope
 *     fields are specified.
 *   - `type` -- the command's operand names the type for the whole call, so a per-entry type could
 *     only agree with it or contradict it. Refusing is what keeps every validation error's
 *     suggested fix (`asc record <type> --prop=…`, generated by `core/state.ts`) a command that
 *     actually works.
 *
 * **Unknown keys are refused rather than ignored**, for the reason `document.ts` gives: a document
 * is written by a model, and `evidenceText` where the field is `evidence_text` is the likely
 * mistake. Ignoring it would record the entry with no evidence text while reporting success.
 */

import { refusal } from './errors.js';
import { describeValue, fieldError, isJsonObject } from './json-fields.js';

/**
 * One entry to record, as the document expresses it.
 *
 * Snake_case, matching the database columns and `asc types export` rather than the store's
 * camelCase `RecordContext`: the document is a wire format a model writes, and the rest of the CLI
 * already exposes the column vocabulary. The mapping to `RecordContext` happens in one place
 * (`commands/record.ts`), and every key is named explicitly there -- a spread would carry whatever
 * a caller sent into a store call that only validates part of it.
 */
export interface EntryDocument {
  readonly properties?: Readonly<Record<string, unknown>>;
  readonly na?: readonly string[];
  /** Absent means "mint one". Present means the caller needs a stable reference. */
  readonly id?: string;
  /** Pins the type version. Absent means the latest registered version. */
  readonly version?: number;
  readonly evidence_text?: string;
  readonly run_id?: string;
  readonly workflow?: string;
  readonly actor?: string;
}

/** The fields an entry document may carry. Anything else is refused. */
const KNOWN_KEYS = [
  'properties',
  'na',
  'id',
  'version',
  'evidence_text',
  'run_id',
  'workflow',
  'actor',
] as const;

/**
 * Keys that an entry document may plausibly carry and never may, with the reason.
 *
 * A map rather than a second list because the reason is the useful part of the message, and a
 * generic "unknown field" would send a caller looking for a spelling mistake that is not there.
 */
const FORBIDDEN_KEYS: Readonly<Record<string, string>> = {
  source:
    "'source' records whether ascend OBSERVED this or DERIVED it, so only the thing doing the " +
    'deriving may set it. An entry recorded by hand or by a command is always source "self".',
  recorded_at:
    "'recorded_at' is read from ascend's clock when the entry is written. A document that could " +
    'set it could backdate an entry, and the ledger sorts chronologically by that column alone.',
  cwd: "'cwd' is read from the process rather than asked for. Omit it.",
  repo: "'repo' is derived from the working directory and is not read yet (E5). Omit it.",
  git_sha: "'git_sha' is derived from the working directory and is not read yet (E5). Omit it.",
  branch: "'branch' is derived from the working directory and is not read yet (E5). Omit it.",
  type:
    'the type is the command operand: `asc record <type> …`. One call records one type, so a ' +
    'per-entry type could only repeat it or contradict it.',
  type_name: 'the type is the command operand: `asc record <type> …`. Omit it.',
  properties_json:
    "'properties' is the field for values; it is stored as JSON but is not spelled that way here.",
  na_json:
    "'na' is the field for not-applicable properties; it is stored as JSON, not spelled that way.",
};

function parseEntry(source: string, where: string, raw: unknown): EntryDocument {
  if (!isJsonObject(raw)) fieldError(source, where, 'a JSON object', raw);

  for (const key of Object.keys(raw)) {
    const forbidden = FORBIDDEN_KEYS[key];
    if (forbidden !== undefined) {
      throw refusal(
        `${source}: ${where} carries '${key}', which cannot be set here -- ${forbidden}`,
      );
    }
    if (!(KNOWN_KEYS as readonly string[]).includes(key)) {
      throw refusal(
        `${source}: ${where} has no such field '${key}'. The fields are: ${KNOWN_KEYS.join(', ')}. ` +
          `Fields are not ignored when unrecognised, so that a misspelt one cannot be dropped in silence.`,
      );
    }
  }

  const properties = raw['properties'];
  if (properties !== undefined && !isJsonObject(properties)) {
    fieldError(
      source,
      `${where}.properties`,
      'a JSON object of property names to values',
      properties,
    );
  }

  const na = raw['na'];
  if (na !== undefined) {
    if (!Array.isArray(na) || na.some((name) => typeof name !== 'string')) {
      fieldError(source, `${where}.na`, 'an array of property names', na);
    }
  }

  const id = raw['id'];
  if (id !== undefined) {
    if (typeof id !== 'string') fieldError(source, `${where}.id`, 'a string', id);
    // Checked here rather than left to the store, which refuses an empty id at record time with a
    // message about SQLite semantics. `''` as an id is a document mistake, and it is cheaper to say
    // so where the document is being read.
    if (id === '') {
      throw refusal(
        `${source}: ${where}.id is empty. Omit 'id' to have ascend mint one, or give a real ` +
          `identifier -- an empty string is a real value, so it would be stored as one.`,
      );
    }
  }

  const version = raw['version'];
  if (version !== undefined) {
    if (!Number.isInteger(version) || (version as number) < 1) {
      throw refusal(
        `${source}: ${where}.version must be a whole number of 1 or more, but it is ` +
          `${describeValue(version)}. Versions are numbered from 1 without gaps.`,
      );
    }
  }

  for (const key of ['evidence_text', 'run_id', 'workflow', 'actor'] as const) {
    const value = raw[key];
    if (value !== undefined && typeof value !== 'string') {
      fieldError(source, `${where}.${key}`, 'a string', value);
    }
    // `''` is refused by the store's `requireNonEmpty` at record time with the same reasoning, and
    // it is repeated here so the failure names the document field rather than the store field.
    if (value === '') {
      throw refusal(
        `${source}: ${where}.${key} is empty. An empty string is a real value in SQLite rather ` +
          `than "unknown", so omit the field instead to leave it unset.`,
      );
    }
  }

  // Built field by field rather than spread: `exactOptionalPropertyTypes` is on, so an explicit
  // `undefined` is a different type from an absent key, and a spread of raw JSON would carry every
  // key it saw -- including ones that must stay absent.
  return {
    ...(properties === undefined ? {} : { properties: properties }),
    ...(na === undefined ? {} : { na: na as string[] }),
    ...(id === undefined ? {} : { id: id }),
    ...(version === undefined ? {} : { version: version as number }),
    ...(raw['evidence_text'] === undefined
      ? {}
      : { evidence_text: raw['evidence_text'] as string }),
    ...(raw['run_id'] === undefined ? {} : { run_id: raw['run_id'] as string }),
    ...(raw['workflow'] === undefined ? {} : { workflow: raw['workflow'] as string }),
    ...(raw['actor'] === undefined ? {} : { actor: raw['actor'] as string }),
  };
}

/**
 * Parse `text` as one entry document or a batch of them.
 *
 * `source` names where the text came from (a path, or `standard input`) so every error can say
 * which document it is about -- with a batch, "which one?" is the first thing a caller needs.
 */
export function parseEntryDocuments(text: string, source: string): readonly EntryDocument[] {
  let raw: unknown;
  try {
    raw = JSON.parse(text) as unknown;
  } catch (error) {
    throw refusal(
      `${source} is not valid JSON: ${error instanceof Error ? error.message : String(error)}.`,
    );
  }

  if (Array.isArray(raw)) {
    if (raw.length === 0) {
      throw refusal(
        `${source} is an empty array, so there is nothing to record. An empty document is not a ` +
          `successful recording of zero entries -- it is a caller that produced nothing.`,
      );
    }
    return raw.map((entry, index) => parseEntry(source, `[${String(index)}]`, entry));
  }

  return [parseEntry(source, 'the document', raw)];
}
